# Generated by Django 4.0.4 on 2022-05-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(blank=True, max_length=20, null=True)),
                ("end_time", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "lesson",
            },
        ),
        migrations.CreateModel(
            name="Role1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "role1",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advisor", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "section",
            },
        ),
        migrations.CreateModel(
            name="Weekday1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_day", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "weekday1",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_student",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("roll_no", models.CharField(blank=True, max_length=20, null=True)),
                ("amount_fee", models.IntegerField(blank=True, null=True)),
                ("fee_date", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "id_section",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_section",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.section",
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_staff", models.CharField(blank=True, max_length=20, null=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
                (
                    "roles",
                    models.ManyToManyField(related_name="staffs", to="core.role1"),
                ),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.AddField(
            model_name="section",
            name="id_staff",
            field=models.ForeignKey(
                blank=True,
                db_column="id_staff",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.staff",
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField(blank=True, null=True)),
                (
                    "id_class",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_class",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.class",
                    ),
                ),
                (
                    "id_lesson",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_lesson",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.lesson",
                    ),
                ),
                (
                    "id_section",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_section",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.section",
                    ),
                ),
                (
                    "id_staff",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_staff",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.staff",
                    ),
                ),
                (
                    "id_wk",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_wk",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.weekday1",
                    ),
                ),
            ],
            options={
                "db_table": "schedule",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="id_staff",
            field=models.ForeignKey(
                blank=True,
                db_column="id_staff",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.staff",
            ),
        ),
    ]
